import Head from "next/head";
import Link from "next/link";
import { appRouter } from "~/server/api/root";

const Search = async ({
  params,
}: {
  params: {
    name: string;
  };
}) => {
  const { name } = params;

  const caller = appRouter.createCaller({});

  const data = await caller.artist.search({ text: name || "" });

  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{name}</h1>
        <ul>
          {data?.artist.map((artist) => (
            <li key={artist.mbid}>
              <Link
                href="/artist/id/[id]/search-settings"
                as={`/artist/id/${encodeURIComponent(
                  artist.mbid
                )}/search-settings`}
              >
                {artist.name}
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Search;
