import "~/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen items-center justify-center bg-spotify-header">
          <div className="relative h-[95vh] w-[95vw] rounded-lg bg-spotify-background p-4 shadow-md md:h-[35rem] md:w-96">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
