import "~/styles/globals.css";
import { ClientProvider } from "~/utils/trpcClient";
import { LoggedSpotifyUser } from "./stores/logged-spotify-user";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProvider>
      <LoggedSpotifyUser />
      <html lang="en">
        <body className="select-none">
          <div className="flex h-screen items-center justify-center bg-spotify-header pb-10 md:pb-0">
            <div className="relative h-[95vh] w-[95vw] rounded-lg bg-spotify-background px-4 py-4 shadow-md md:h-[40rem] md:w-96">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClientProvider>
  );
}
